worker_processes 1;
events { 
    worker_connections 1024; 
 }
http {
  default_type text/plain;
  server {
    listen 3000;
    server_name localhost;
    rewrite ^/old-products/(\d+)$ /products/$1 permanent;
    location = /products { 
        if ($arg_id) { 
            return 301 /products/$arg_id; 
        } return 400 "missing id"; 
    }
    location ~ ^/products/(\d+)$ { 
        return 200 "product:$1"; 
    }
    location / { 
        try_files $uri $uri/ =404; 
    }
  }
}