worker_processes 1;
events { 
    worker_connections 1024; 
 }
http {
  default_type text/plain;
  upstream flask_backend {
    server 127.0.0.1:5000 max_fails=1 fail_timeout=5s;
    server 127.0.0.1:5001 max_fails=1 fail_timeout=5s;
    server 127.0.0.1:5002 max_fails=1 fail_timeout=5s;
  }
  server {
    listen 3000;
    server_name localhost;
    error_page 404 /custom_404.html;
    error_page 502 /custom_502.html;
    rewrite ^/old-products/(\d+)$ /products/$1 permanent;
    location = /products { 
        if ($arg_id) { 
            return 301 /products/$arg_id; 
        } return 400 "missing id"; 
    }
    location ~ ^/products/(\d+)$ { 
        return 200 "product:$1"; 
    }
    location / { 
        try_files $uri $uri/ =404; 
    }

    location /upstream { 
        proxy_pass http://127.0.0.1:5999;
    }
    location = /custom_404.html { 
        return 404 "<!doctype html><title>404</title><h1>Not Found</h1>"; 
    }
    location = /custom_502.html { 
        return 502 "<!doctype html><title>502</title><h1>Bad Gateway</h1>"; 
    }
    location /api/ {
      proxy_next_upstream error timeout http_502 http_503 http_504;
      proxy_pass http://flask_backend/;
    }
    location /health {
      proxy_pass http://flask_backend/status;
    }
  }
}