worker_processes 1;
events { 
    worker_connections 1024; 
}
http {
  include mime.types;
  default_type text/plain;
  server {
    listen 3000;
    server_name localhost;
    location / { 
        return 200 "OK"; 
    }
    location /admin/ {
      auth_basic "Restricted Area";
      auth_basic_user_file .htpasswd;
      try_files "" @admin_ok;
    }
    location @admin_ok {
      add_header X-Auth "basic" always;
      return 200 "admin";
    }
  }
}